root: true
extends:
  - airbnb
env:
  es6: false
  browser: true
globals:
  expect: true
  it: true
  describe: true
  Drupal: true
rules:
  strict: 0
  import/no-extraneous-dependencies: 0
  quotes: [ 2, "single", { "avoidEscape": true, "allowTemplateLiterals": true } ]
