<?php

/**
 * @file
 * Development module for CivicTheme Source site.
 */

declare(strict_types=1);

use Drupal\civictheme\CivicthemeVersionManager;
use Drupal\Core\Site\Settings;

/**
 * Implements hook_mail_alter().
 */
function civictheme_dev_mail_alter(array &$message): void {
  // Allow to stop any mail send out through settings. Note if email
  // functionality needs to be tested, this code should be removed and
  // replaced with a dev mail system.
  if (Settings::get('suspend_mail_send')) {
    $message['send'] = FALSE;
  }
}

/**
 * Implements hook_preprocess_html().
 */
function civictheme_dev_preprocess_html(array &$variables): void {
  /** @var \Drupal\civictheme\CivicthemeVersionManager $version_manager */
  $version_manager = \Drupal::classResolver(CivicthemeVersionManager::class);
  $variables['page_bottom']['civictheme_version'] = $version_manager->render('body');
}

/**
 * Implements hook_styleguide_alter().
 */
function civictheme_dev_styleguide_alter(array &$items): void {
  // Remove password_confirm field from the form as CivicTheme does not support
  // it.
  unset($items['form']['content']['password_confirm']);
}
