<?php

/**
 * @file
 * Install file for core.
 */

declare(strict_types=1);

use Drupal\user\Entity\User;

/**
 * Implements hook_install().
 */
function civictheme_dev_install(): void {
  // Assign user 1 the "administrator" role.
  /** @var \Drupal\user\Entity\User $user */
  $user = User::load(1);
  $user->addRole('administrator');
  $user->save();

  \Drupal::moduleHandler()->loadInclude('civictheme_dev', 'php', 'civictheme_dev.post_update');
  $functions = get_defined_functions();

  // Run all update functions when installing this module.
  foreach ($functions['user'] as $function) {
    if (str_starts_with($function, 'civictheme_dev_update_')) {
      $sandbox = [];
      call_user_func($function, $sandbox);
    }
  }

  // Run all post-update functions when installing this module.
  $key_value = \Drupal::keyValue('post_update');
  $executed_updates = $key_value->get('existing_updates', []);
  foreach ($executed_updates as $function) {
    if (str_starts_with((string) $function, 'civictheme_dev_post_update_')) {
      print sprintf('Running post-update function: %s%s', $function, PHP_EOL);
      $sandbox = [];
      $ret = call_user_func($function, $sandbox);
      if (is_string($ret)) {
        print $ret . PHP_EOL;
      }
    }
  }
}
