<?php

/**
 * @file
 * Install file for core.
 */

use Drupal\user\Entity\User;

/**
 * Implements hook_install().
 */
function civictheme_dev_install() {
  // Assign user 1 the "administrator" role.
  /** @var \Drupal\user\Entity\User $user */
  $user = User::load(1);
  $user->roles[] = 'administrator';
  $user->save();

  module_load_include('php', 'civictheme_dev', 'civictheme_dev.post_update');
  $functions = get_defined_functions();

  // Run all update functions when installing this module.
  foreach ($functions['user'] as $function) {
    if (strpos($function, 'civictheme_dev_update_') === 0) {
      $sandbox = [];
      call_user_func($function, $sandbox);
    }
  }

  // Run all post-update functions when installing this module.
  $key_value = \Drupal::keyValue('post_update');
  $executed_updates = $key_value->get('existing_updates', []);
  foreach ($executed_updates as $function) {
    if (strpos($function, 'civictheme_dev_post_update_') === 0) {
      $sandbox = [];
      call_user_func($function, $sandbox);
    }
  }
}
