<?php

/**
 * @file
 * Civic default content module.
 */

/**
 * Implements hook_module_implements_alter().
 */
function civic_default_content_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'modules_installed') {
    $group = $implementations['civic_default_content'];
    unset($implementations['civic_default_content']);
    $implementations['civic_default_content'] = $group;
  }
}

/**
 * Implements hook_modules_installed().
 */
function civic_default_content_modules_installed($modules, $is_syncing) {
  if (in_array('civic_default_content', $modules)) {
    module_load_include('php', 'civic_default_content', 'civic_default_content.post_update');
    // Run all post-update functions when installing this module.
    $key_value = \Drupal::keyValue('post_update');
    $executed_updates = $key_value->get('existing_updates', []);
    foreach ($executed_updates as $function) {
      if (strpos($function, 'civic_default_content_post_update_') === 0) {
        $sandbox = [];
        call_user_func($function, $sandbox);
      }
    }
  }
}
