<?php

/**
 * @file
 * Install file for civic_default_content.
 */

/**
 * Implements hook_install().
 */
function civic_default_content_install() {
  $functions = get_defined_functions();
  // Run all update functions when installing this module.
  foreach ($functions['user'] as $function) {
    if (strpos($function, 'civic_default_content_update_') === 0) {
      $sandbox = [];
      call_user_func($function, $sandbox);
    }
  }
}
