<?php


//function civic_preprocess_media(array &$variables) {
//  dpm($variables['elements']['#media']);
////
////  $variables['media'] = $variables['elements']['#media'];
////  $variables['view_mode'] = $variables['elements']['#view_mode'];
////  $variables['name'] = $variables['media']
////    ->label();
////
////  // Helpful $content variable for templates.
////  foreach (Element::children($variables['elements']) as $key) {
////    $variables['content'][$key] = $variables['elements'][$key];
////  }
//}
