<?php

/**
 * @file
 * CivicTheme default content module.
 */

declare(strict_types=1);

/**
 * Helper for implementations of hook_module_implements_alter().
 */
function _civictheme_content_module_implements_alter(string $module, array &$implementations, string $hook): void {
  if ($hook === 'modules_installed') {
    $group = $implementations[$module];
    unset($implementations[$module]);
    $implementations[$module] = $group;
  }
}

/**
 * Helper for implementations of hook_modules_installed().
 */
function _civictheme_content_modules_installed(string $module, array $modules): void {
  if (in_array($module, $modules)) {
    \Drupal::moduleHandler()->loadInclude($module, 'php', $module . '.post_update');
    // Run all post-update functions when installing this module.
    $key_value = \Drupal::keyValue('post_update');
    $executed_updates = $key_value->get('existing_updates', []);
    foreach ($executed_updates as $function) {
      if (str_starts_with((string) $function, $module . '_post_update_')) {
        $sandbox = [];
        call_user_func($function, $sandbox);
      }
    }
  }
}
