<?php

/**
 * @file
 * CivicTheme default content module.
 */

/**
 * Helper for implementations of hook_module_implements_alter().
 */
function _civictheme_content_module_implements_alter($module, &$implementations, $hook) {
  if ($hook == 'modules_installed') {
    $group = $implementations[$module];
    unset($implementations[$module]);
    $implementations[$module] = $group;
  }
}

/**
 * Helper for implementations of hook_modules_installed().
 */
function _civictheme_content_modules_installed($module, $modules) {
  if (in_array($module, $modules)) {
    module_load_include('php', $module, $module . '.post_update');
    // Run all post-update functions when installing this module.
    $key_value = \Drupal::keyValue('post_update');
    $executed_updates = $key_value->get('existing_updates', []);
    foreach ($executed_updates as $function) {
      if (strpos($function, $module . '_post_update_') === 0) {
        $sandbox = [];
        call_user_func($function, $sandbox);
      }
    }
  }
}
