<?php

/**
 * @file
 * Core module for Cs.
 */

use Drupal\Core\Site\Settings;

/**
 * Implements hook_mail_alter().
 */
function cs_core_mail_alter(&$message) {
  // Allow to stop any mail send out through settings. Note if email
  // functionality needs to be tested, this code should be removed and
  // replaced with a dev mail system.
  if (Settings::get('suspend_mail_send')) {
    $message['send'] = FALSE;
  }
}

/**
 * Implements hook_preprocess_html().
 */
function cs_core_preprocess_html(&$variables) {
  /** @var \Drupal\Core\Extension\ThemeExtensionList $theme_extension_list */
  $civictheme_path = \Drupal::service('extension.list.theme')->getPath('civictheme');
  $civictheme_theme_path = $civictheme_path . DIRECTORY_SEPARATOR . 'civictheme.theme';
  if (!file_exists($civictheme_theme_path)) {
    return;
  }

  require_once $civictheme_theme_path;

  $version = civictheme_get_version();

  if ($version) {
    $style = <<<HTML
<style>
.ct-footer__logo {
  position: relative;
}
.ct-footer__logo::after {
  content: 'Version $version';
  bottom: 0;
  display: block;
  font-family: sans-serif;
  font-size: x-small;
  left: 50px;
  position: absolute;
}
</style>
HTML;

    $variables['page_bottom']['civictheme_version'] = [
      '#type' => 'inline_template',
      '#template' => '{{ content|raw }}',
      '#context' => [
        'content' => $style,
      ],
    ];
  }
}
