<?php

/**
 * @file
 * CivicTheme migrate module.
 */

use Drupal\civictheme_migrate\Form\MigrationEditFormAlter;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\FileInterface;

/**
 * Validation handler for migration file.
 *
 * @param \Drupal\file\FileInterface $file
 *   File instance to validate.
 * @param string $migration_schema_id
 *   The migration schema ID.
 *
 * @return array
 *   Array of errors.
 */
function civictheme_migrate_validate_migration_schema(FileInterface $file, string $migration_schema_id): array {
  /** @var \Drupal\civictheme_migrate\MigrationFileValidator $validator */
  $validator = \Drupal::getContainer()->get('civictheme_migrate.migration_file_validator');

  return $validator->validate($migration_schema_id, $file->getFileUri());
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function civictheme_migrate_form_migration_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::classResolver(MigrationEditFormAlter::class)->formAlter($form, $form_state, $form_id);
}
