<?php

/**
 * @file
 * CivicTheme Higher Education Content module.
 */

declare(strict_types=1);

/**
 * Implements hook_module_implements_alter().
 */
function civictheme_content_highereducation_module_implements_alter(array &$implementations, string $hook): void {
  $module = 'civictheme_content_highereducation';
  if ($hook === 'modules_installed') {
    $group = $implementations[$module];
    unset($implementations[$module]);
    $implementations[$module] = $group;
  }
}

/**
 * Implements hook_modules_installed().
 */
function civictheme_content_highereducation_modules_installed(array $modules, bool $is_syncing): void {
  _civictheme_content_modules_installed('civictheme_content_highereducation', $modules);
}
