<?php

/**
 * @file
 * CivicTheme Higher Education Content module.
 */

/**
 * Implements hook_module_implements_alter().
 */
function civictheme_content_highereducation_module_implements_alter(&$implementations, $hook) {
  _civictheme_content_module_implements_alter('civictheme_content_highereducation', $implementations, $hook);
}

/**
 * Implements hook_modules_installed().
 */
function civictheme_content_highereducation_modules_installed($modules, $is_syncing) {
  _civictheme_content_modules_installed('civictheme_content_highereducation', $modules);
}
