# Schema for the configuration files of the CivicTheme theme.

civictheme.settings:
  type: theme_settings
  label: 'CivicTheme settings'
  mapping:
    components:
      type: mapping
      label: 'Components settings'
      mapping:
        logo:
          type: mapping
          label: 'Logo settings'
          mapping:
            image_primary_light_desktop:
              label: 'Logo primary image in light theme for desktop'
              type: string
            image_primary_light_mobile:
              label: 'Logo primary image in light theme for mobile'
              type: string
            image_primary_dark_desktop:
              label: 'Logo primary image in dark theme for desktop'
              type: string
            image_primary_dark_mobile:
              label: 'Logo primary image in dark theme for mobile'
              type: string
            image_secondary_light_desktop:
              label: 'Logo secondary image in light theme for desktop'
              type: string
            image_secondary_light_mobile:
              label: 'Logo secondary image in light theme for mobile'
              type: string
            image_secondary_dark_desktop:
              label: 'Logo secondary image in dark theme for desktop'
              type: string
            image_secondary_dark_mobile:
              label: 'Logo secondary image in dark theme for mobile'
              type: string
            image_alt:
              label: 'Logo image "alt" text'
              type: string
        header:
          type: mapping
          label: 'Header settings'
          mapping:
            theme:
              label: 'Theme'
              type: string
            logo_type:
              label: 'Logo type'
              type: string
        navigation:
          type: mapping
          label: 'Navigation settings'
          mapping:
            primary_navigation:
              type: mapping
              label: 'Primary navigation settings'
              mapping:
                dropdown:
                  label: 'Dropdown type'
                  type: string
                dropdown_columns:
                  label: 'Number of columns in dropdown'
                  type: boolean
                dropdown_columns_fill:
                  label: 'Fill width of the last dropdown row'
                  type: boolean
                is_animated:
                  label: 'Animate transition'
                  type: boolean
            secondary_navigation:
              type: mapping
              label: 'Primary navigation settings'
              mapping:
                dropdown:
                  label: 'Dropdown type'
                  type: string
                dropdown_columns:
                  label: 'Number of columns in dropdown'
                  type: boolean
                dropdown_columns_fill:
                  label: 'Fill width of the last dropdown row'
                  type: boolean
                is_animated:
                  label: 'Animate transition'
                  type: boolean
        footer:
          type: mapping
          label: 'Footer settings'
          mapping:
            theme:
              label: 'Theme'
              type: string
            logo_type:
              label: 'Logo type'
              type: string
            background_image:
              label: 'Footer background image'
              type: string
        link:
          type: mapping
          label: 'Link settings'
          mapping:
            new_window:
              label: 'Open all links in the new window'
              type: boolean
            external_new_window:
              label: 'Open external links in the new window'
              type: boolean
            external_override_domains:
              label: 'List of override domains for external links'
              type: sequence
              sequence:
                type: string
