<?php

/**
 * @file
 * Civic Default Demo Content module.
 */

/**
 * Implements hook_module_implements_alter().
 */
function civic_default_content_demo_module_implements_alter(&$implementations, $hook) {
  _civic_default_content_module_implements_alter('civic_default_content_demo', $implementations, $hook);
}

/**
 * Implements hook_modules_installed().
 */
function civic_default_content_demo_modules_installed($modules, $is_syncing) {
  _civic_default_content_modules_installed('civic_default_content_demo', $modules);
}
