# Schema for the configuration files of CivicTheme Migrate.

civictheme_migrate.settings:
  type: config_object
  label: 'CivicTheme Migrate settings'
  mapping:
    migration_type:
      label: 'Migration type'
      type: string
      nullable: true
    remote:
      label: 'Remote migration settings'
      type: mapping
      mapping:
        auth_type:
          label: 'Remote files authentication type'
          type: string
          nullable: true
        auth_username:
          label: 'Username'
          type: string
          nullable: true
        auth_password:
          label: 'Password'
          type: string
          nullable: true
        auth_token:
          label: 'API token'
          type: string
          nullable: true
        content_endpoint:
          label: 'Remote Page JSON Endpoints'
          type: string
          nullable: true
        media_endpoint:
          label: 'Remote Media JSON Endpoints'
          type: string
          nullable: true
    configuration_files:
      label: 'List of JSON files'
      type: 'sequence'
      nullable: true
      sequence:
        label: 'Migration file info'
        type: 'string'

