<?php

/**
 * @file
 * CivicTheme Default Demo Content module.
 */

/**
 * Implements hook_module_implements_alter().
 */
function civictheme_content_default_module_implements_alter(&$implementations, $hook) {
  _civictheme_content_module_implements_alter('civictheme_content_default', $implementations, $hook);
}

/**
 * Implements hook_modules_installed().
 */
function civictheme_content_default_modules_installed($modules, $is_syncing) {
  _civictheme_content_modules_installed('civictheme_content_default', $modules);
}
