<?php

/**
 * @file
 * CivicTheme Default Corporate Content module.
 */

declare(strict_types=1);

/**
 * Implements hook_module_implements_alter().
 */
function civictheme_content_corporate_module_implements_alter(array &$implementations, string $hook): void {
  _civictheme_content_module_implements_alter('civictheme_content_corporate', $implementations, $hook);
}

/**
 * Implements hook_modules_installed().
 */
function civictheme_content_corporate_modules_installed(array $modules, bool $is_syncing): void {
  _civictheme_content_modules_installed('civictheme_content_corporate', $modules);
}
