<?php

/**
 * @file
 * Main functions.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_delete().
 */
function cs_demo_entity_delete(EntityInterface $entity) {
  try {
    Database::getConnection()->delete('cs_demo')
      ->condition('entity_type', $entity->getEntityTypeId())
      ->condition('bundle', $entity->bundle())
      ->condition('entity_id', $entity->id())
      ->execute();
  }
  catch (Exception $exception) {
    watchdog_exception('cs_demo', $exception);
  }
}

/**
 * Implements hook_config_ignore_settings_alter().
 */
function cs_demo_config_ignore_settings_alter(array &$settings) {
  // Exclude module from being enabled or disabled.
  $settings[] = 'core.extension:module.cs_demo';
}
