##
# GitHub Actions workflow to dispatch a PR webhook for a Pull Request.
#
# This is used to allow more granular control over the operations that trigger
# webhooks.
#
# Note that Lagoon's webhook should be disabled in GitHub.

name: Dispatch a webhook to Lagoon when Pull Request is closed

on:
  pull_request:
    types: [closed]

jobs:
  dispatch_webhook_lagoon_remove_environment_pr_closed:
    runs-on: ubuntu-latest
    steps:
      - name: Remove environment after a PR is closed
        run: |
          cat $GITHUB_EVENT_PATH | curl \
            -X POST \
            --header "Content-Type: application/json" \
            --header "X-GitHub-Delivery: ${RUNNER_TRACKING_ID:7}" \
            --header "X-GitHub-Event: pull_request" \
            --data-binary @- \
            https://hooks.lagoon.amazeeio.cloud/
