name: 'Storybook Tests'
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.14'
      - name: Install dependencies
        run: npm install
        working-directory: docroot/themes/contrib/civictheme/civictheme_library
      - name: Build Storybook
        run: npm run build-storybook
        working-directory: docroot/themes/contrib/civictheme/civictheme_library
      - name: Run tests
        run: npm run test
        working-directory: docroot/themes/contrib/civictheme/civictheme_library
